export const ErrorCode = {
  ERR_OVERWRITE_PROTECTED_BRANCH: 'ERR_OVERWRITE_PROTECTED_BRANCH',
  ERR_VERSION_EXISTS: 'ERR_VERSION_EXISTS',
  ERR_ZIP_TRAVERSAL: 'ERR_ZIP_TRAVERSAL',
  ERR_ZIP_SYMLINK: 'ERR_ZIP_SYMLINK',
  ERR_ZIP_COLLISION: 'ERR_ZIP_COLLISION',
  ERR_ZIP_UNEXPECTED_ENTRY: 'ERR_ZIP_UNEXPECTED_ENTRY',
  ERR_ZIP_MALFORMED_ENTRY: 'ERR_ZIP_MALFORMED_ENTRY',
  ERR_ZIP_VERSIONS_INCLUDED: 'ERR_ZIP_VERSIONS_INCLUDED',
  ERR_ZIP_DISALLOWED_PAYLOAD: 'ERR_ZIP_DISALLOWED_PAYLOAD',
  ERR_FRONTMATTER_VERSION_MISMATCH: 'ERR_FRONTMATTER_VERSION_MISMATCH',
  ERR_CHECKSUM_MISMATCH: 'ERR_CHECKSUM_MISMATCH',
  ERR_MANUAL_MUTATION: 'ERR_MANUAL_MUTATION',
  ERR_VALIDATION_FAILED: 'ERR_VALIDATION_FAILED',
  ERR_PACKAGE_NOT_FOUND: 'ERR_PACKAGE_NOT_FOUND',
  ERR_METADATA_INVALID: 'ERR_METADATA_INVALID',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export class PackageError extends Error {
  readonly code: ErrorCode;

  constructor(code: ErrorCode, message: string) {
    super(message);
    this.name = 'PackageError';
    this.code = code;
  }
}
